### ISSUE TITLE
Remove dependency on Funclate

### ISSUE THREAD

**Issue by jshiell** [bodar/utterlyidle#11]
It'd be absolutely smashing if we could remove the dependency on Funulate, and also breaking the transitive dependency on ST3. Thanks!

**Comment by danielbodart** [comment]
James do you care about this being back ported to V1?

**Comment by jshiell** [comment]
Not a huge worry at present, tbh. The current setup works, and I presume we'll be migrating to V2 as soon as it's stable. Speaking of which, any idea what sort of timeframe we're looking at for that? Thanks!

**Comment by danielbodart** [comment]
Won't fix on V1
