### ISSUE TITLE
NormaliseUriHandler conflicts with BasePathHandler

### ISSUE THREAD

**Issue by spmiller** [bodar/utterlyidle#2]
When both the NormaliseUriHandler and the BasePathHandler are used (they are both enabled by default), the BasePathHandler fails to work correctly.

Let's say the BasePath is set to `/foo/`. The BasePathHandler is meant to remove `/foo/` from all requests so you don't have to specify the whole path in the resource -- eg, `/foo/bar` will be converted to just `bar`.

The NormaliseUriHandler kicks in beforehand though, and will change any request to `/foo/` to be `/foo`, which obviously doesn't match the BasePath.

This is an edge case, but it's quite annoying for the first request!

Pull Request #1 includes a failing test for this issue.

**Comment by danielbodart** [comment]
Stu did I fix this already?

**Comment by spmiller** [comment]
Yep, I think so!
