### ISSUE TITLE
Consistency changes to @Path in v1.84

### ISSUE THREAD

**Issue by daviddenton** [bodar/utterlyidle#50]
We have fixed a bug in UriTemplate which was causing the template to `match()` a path but then blow up during `extract()` of the PathParams contained within:

A template of `{name}/{unused:end$}` would match the path `/value/end/` but then blow up. This occurs because the `match()` operation trims the slashes from the front and end of the path, but the `extract()` didn't do this.

We have  fixed this to be consistent in v1.84, but has revealed an inconsistency in how the path parameters are handled (in terms of the values returned) between the first and subsequent PathParams. The change means that `@Path("{first}/{second}")` matches against `/my/uri` as `first -> my` and `second -> uri`. Previously, `first` would have NOT had the leading slash dropped (ie. `/my`).

This does represent a change in behaviour, but we now get more consistent results instead of a bug, as both start and end slashes are dropped. We saw only 2 options and took the one which we considered to be better:
1. Drop both the leading and ending slashes (this is v1.84 behaviour)
2. Drop the ending slash only. Less "breaky", but inconsistent.

Any opinions gratefully received! Check out UriTemplateTest for the cases that we covered.

**Comment by danielbodart** [comment]
If anyone has an issue with the change or a better solution please let us know.

Thanks Denton ;)
